# Task 2 - SQL for Data Extraction

## Objective
To perform data extraction and business analysis using SQL and SQLite, and integrate SQL queries with Python using Pandas.

### Tools Used
- SQLite
- Python
- Pandas
- Jupyter Notebook

In [30]:
import pandas as pd
import sqlite3

In [31]:
conn = sqlite3.connect("../data/database/superstore.db")

print("Database Connected Successfully")

Database Connected Successfully

In [32]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

         name
0  superstore

In [33]:
query = """
SELECT *
FROM superstore
LIMIT 5;
"""

pd.read_sql(query, conn)

,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,sales,quantity,discount,profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.96,2,0.0,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.94,3,0.0,219.582
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.62,2,0.0,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.031
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.368,2,0.2,2.5164

# Business Question 1

Which region generates the highest profit?

In [34]:
query = """
SELECT
    region,
    ROUND(SUM(CAST(profit AS REAL)),2) AS total_profit
FROM superstore
GROUP BY region
ORDER BY total_profit DESC;
"""

pd.read_sql(query, conn)

    region  total_profit
0     West     108329.81
1     East      91506.31
2    South      46749.43
3  Central      39655.88

# Business Question 2

Which are the Top 5 Cities by Sales?

In [35]:
query = """
SELECT
    city,
    ROUND(SUM(CAST(sales AS REAL)),2) AS total_sales
FROM superstore
GROUP BY city
ORDER BY total_sales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

            city  total_sales
0  New York City    256319.04
1    Los Angeles    175831.90
2        Seattle    119460.28
3  San Francisco    112577.17
4   Philadelphia    109061.46

# Business Question 3

Which category generates the highest sales?

In [36]:
query = """
SELECT
    category,
    ROUND(SUM(CAST(sales AS REAL)),2) AS total_sales
FROM superstore
GROUP BY category
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

          category  total_sales
0       Technology    836154.03
1        Furniture    741306.31
2  Office Supplies    718735.24

# Business Question 4

Which category generates the highest profit?

In [37]:
query = """
SELECT
    category,
    ROUND(SUM(CAST(profit AS REAL)),2) AS total_profit
FROM superstore
GROUP BY category
ORDER BY total_profit DESC;
"""

pd.read_sql(query, conn)

          category  total_profit
0       Technology     145454.95
1  Office Supplies     122364.66
2        Furniture      18421.81

# Business Question 5

What are the Top 5 Products (Sub-Categories) by Sales?

In [38]:
query = """
SELECT
    sub_category,
    ROUND(SUM(CAST(sales AS REAL)),2) AS total_sales
FROM superstore
GROUP BY sub_category
ORDER BY total_sales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

  sub_category  total_sales
0       Phones    330007.05
1       Chairs    327777.76
2      Storage    223843.61
3       Tables    206965.53
4      Binders    203409.17

# Business Question 6

Which ship mode is used most frequently?

In [39]:
query = """
SELECT
    ship_mode,
    COUNT(*) AS total_orders
FROM superstore
GROUP BY ship_mode
ORDER BY total_orders DESC;
"""

pd.read_sql(query, conn)

        ship_mode  total_orders
0  Standard Class          5955
1    Second Class          1943
2     First Class          1537
3        Same Day           542

# Business Question 7

Which customer segment generates the highest sales?

In [40]:
query = """
SELECT
    segment,
    ROUND(SUM(CAST(sales AS REAL)),2) AS total_sales
FROM superstore
GROUP BY segment
ORDER BY total_sales DESC;
"""

pd.read_sql(query, conn)

       segment  total_sales
0     Consumer   1160832.77
1    Corporate    706070.13
2  Home Office    429292.68

# Business Question 8

Which states generate the highest profit?

In [41]:
query = """
SELECT
    state,
    ROUND(SUM(CAST(profit AS REAL)),2) AS total_profit
FROM superstore
GROUP BY state
ORDER BY total_profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        state  total_profit
0  California      76330.79
1    New York      74015.46
2  Washington      33368.24
3    Michigan      24428.09
4    Virginia      18597.95
5     Indiana      18382.94
6     Georgia      16250.04
7    Kentucky      11199.70
8   Minnesota      10823.19
9    Delaware       9977.37

# Business Question 9

Which products have sales above the average sales value?

In [42]:
query = """
SELECT *
FROM superstore
WHERE CAST(sales AS REAL) >
(
    SELECT AVG(CAST(sales AS REAL))
    FROM superstore
)
LIMIT 10;
"""

pd.read_sql(query, conn)

,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,sales,quantity,discount,profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.96,2,0.0,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.94,3,0.0,219.582
2,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.031
3,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
4,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.184,9,0.2,85.3092
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,911.424,4,0.2,68.3568
6,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.2,132.5922
7,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,665.88,6,0.0,13.3176
8,Standard Class,Consumer,United States,Orem,Utah,84057,West,Furniture,Tables,1044.63,3,0.0,240.2649
9,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,3083.43,7,0.5,-1665.0522

# Business Question 10

Rank the top cities based on total sales.

In [43]:
query = """
SELECT
    city,
    ROUND(SUM(CAST(sales AS REAL)),2) AS total_sales,
    RANK() OVER
    (
        ORDER BY SUM(CAST(sales AS REAL)) DESC
    ) AS sales_rank
FROM superstore
GROUP BY city
LIMIT 10;
"""

pd.read_sql(query, conn)

            city  total_sales  sales_rank
0  New York City    256319.04           1
1    Los Angeles    175831.90           2
2        Seattle    119460.28           3
3  San Francisco    112577.17           4
4   Philadelphia    109061.46           5
5        Houston     64441.26           6
6        Chicago     48535.98           7
7      San Diego     47521.03           8
8   Jacksonville     44713.18           9
9    Springfield     43054.34          10

# Task 2 Summary

## SQL Concepts Implemented

- SELECT
- WHERE
- ORDER BY
- LIMIT
- GROUP BY
- HAVING
- Subqueries
- CTE (WITH)
- ROW_NUMBER()
- RANK()
- LAG()
- LEAD()
- VIEW

## Key Business Insights

1. West region generated the highest profit.
2. New York City generated the highest sales.
3. Technology category generated the highest sales.
4. Technology category generated the highest profit.
5. Phones were the highest-selling sub-category.
6. Standard Class was the most used shipping mode.
7. Consumer segment generated the highest sales.
8. California generated the highest profit among all states.
9. Several transactions had sales significantly above average.
10. New York City ranked first in total sales.